global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - '/etc/prometheus/alert.rules'
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
            - 'alertmanagers:9093'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: node_exporter
    metrics_path: /metrics
    scrape_interval: 1s
    scheme: http
    static_configs:
        - targets: ['node_exporter:9100']
          labels:
                instance: 'Server cute'
